In [1]:
import numpy as np
import pandas as pd
import torch
from sentence_transformers import SentenceTransformer
from sentence_transformers.util import cos_sim

C:\Users\dohoo\anaconda3\envs\erdos_company_discourse\lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange


In [3]:
df_train = pd.read_parquet('../../data/sst5/sst-5_train.parquet')

In [4]:
df_train.head(20)

truth                                               text  \
0       4  The Rock is destined to be the 21st Century 's...   
1       5  The gorgeously elaborate continuation of `` Th...   
2       4  Singer/composer Bryan Adams contributes a slew...   
3       3  You 'd think by now America would have had eno...   
4       4               Yet the act is still charming here .   
5       5  Whether or not you 're enlightened by any of D...   
6       5  Just the labour involved in creating the layer...   
7       4  Part of the charm of Satin Rouge is that it av...   
8       5  a screenplay more ingeniously constructed than...   
9       4           `` Extreme Ops '' exceeds expectations .   
10      5  Good fun , good action , good acting , good di...   
11      3  You Should Pay Nine Bucks for This : Because y...   
12      5                   Dramas like this make it human .   
13      3  A thunderous ride at first , quiet cadences of...   
14      5  Still , this flick is fun , and host to some t...   
15      4  Australian actor/director John Polson and awar...   
16      4  You walk out of The Good Girl with mixed emoti...   
17      3  Post 9/11 the philosophical message of `` Pers...   
18      5        Absorbing character study by André Turpin .   
19      4  If you love reading and/or poetry , then by al...   

                                              vectors  
0   [0.028988052159547806, -0.009446061216294765, ...  
1   [0.009347192011773586, -0.024268826469779015, ...  
2   [0.008711128495633602, 0.02659982070326805, 0....  
3   [0.02907816506922245, -0.0135031184181571, -0....  
4   [-0.009661787189543247, -0.008504915982484818,...  
5   [-0.012160818092525005, -0.012833962216973305,...  
6   [0.004631729330867529, -0.03409641981124878, -...  
7   [-0.013205086812376976, -0.0012794658541679382...  
8   [0.04255269467830658, -0.03733774647116661, -0...  
9   [-0.0015949866501614451, 0.007372601889073849,...  
10  [0.016034267842769623, 0.011066507548093796, -...  
11  [-0.009373359382152557, 0.03660903126001358, -...  
12  [0.018641652539372444, 0.00287843425758183, -0...  
13  [0.007730103563517332, 0.020881924778223038, 0...  
14  [0.044212669134140015, 0.014000174589455128, -...  
15  [0.02159634418785572, 0.0038784369826316833, -...  
16  [-0.0033865843433886766, -0.000461712916148826...  
17  [0.010466049425303936, -0.024989554658532143, ...  
18  [0.0021847051102668047, -0.012134158052504063,...  
19  [-0.03867142274975777, -0.005805046763271093, ...

In [5]:
model = SentenceTransformer('thenlper/gte-large', device='cuda')

In [5]:
text = df_train['text'].tolist()[6]
text

'Some of the visual flourishes are a little too obvious , but restrained and subtle storytelling , and fine performances make this delicate coming-of-age tale a treat .'

In [6]:
emb = model.encode(text)
emb

array([-0.00089823, -0.02702591,  0.00427189, ...,  0.01366597,
        0.02848142,  0.00013055], dtype=float32)

In [7]:
good = model.encode('good')
bad = model.encode('bad')
positive = model.encode('positive')
negative = model.encode('negative')
vgood = model.encode('very good')
vbad = model.encode('very bad')
vpositive = model.encode('very positive')
vnegative = model.encode('very negative')
neutral = model.encode('neutral')
average = model.encode('average')

In [8]:
print(cos_sim(emb, vgood))
print(cos_sim(emb, vpositive))
print(cos_sim(emb, good))
print(cos_sim(emb, positive))
print(cos_sim(emb, bad))
print(cos_sim(emb, negative))
print(cos_sim(emb, vbad))
print(cos_sim(emb, vnegative))
print(cos_sim(emb, average))
print(cos_sim(emb, neutral))

tensor([[0.7661]])
tensor([[0.7453]])
tensor([[0.7704]])
tensor([[0.7443]])
tensor([[0.7250]])
tensor([[0.6985]])
tensor([[0.7204]])
tensor([[0.7017]])
tensor([[0.7206]])
tensor([[0.7622]])


In [9]:
very = model.encode('very')

In [10]:
print(cos_sim(emb, very))

tensor([[0.7802]])


In [11]:
text2 = df_train['text'].tolist()[3]
text2

"When the precise nature of Matthew 's predicament finally comes into sharp focus , the revelation fails to justify the build-up ."

In [12]:
emb2 = model.encode(text2)

In [13]:
print(cos_sim(emb2, vgood))
print(cos_sim(emb2, vpositive))
print(cos_sim(emb2, good))
print(cos_sim(emb2, positive))
print(cos_sim(emb2, bad))
print(cos_sim(emb2, negative))
print(cos_sim(emb2, vbad))
print(cos_sim(emb2, vnegative))
print(cos_sim(emb2, average))
print(cos_sim(emb2, neutral))

tensor([[0.7329]])
tensor([[0.7265]])
tensor([[0.7480]])
tensor([[0.7431]])
tensor([[0.7689]])
tensor([[0.7689]])
tensor([[0.7752]])
tensor([[0.7794]])
tensor([[0.7360]])
tensor([[0.7613]])


In [14]:
print(cos_sim(emb2, very))

tensor([[0.7661]])


In [15]:
w1 = model.encode('Conversion from radians to degrees')
w2 = model.encode('This model exclusively caters to English texts, and any lengthy texts will be truncated to a maximum of 512 tokens')
print(cos_sim(w1, w2))

tensor([[0.7278]])


In [7]:
model = SentenceTransformer('Alibaba-NLP/gte-large-en-v1.5', trust_remote_code=True)

In [8]:
w1 = model.encode('Conversion from radians to degrees')
w2 = model.encode('This model exclusively caters to English texts, and any lengthy texts will be truncated to a maximum of 512 tokens')
print(cos_sim(w1, w2))

tensor([[0.3583]])


C:\Users\dohoo\.cache\huggingface\modules\transformers_modules\Alibaba-NLP\new-impl\fcceab01127c2ce888844aa365d3195cff389c7c\modeling.py:578: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
